---
title: "Stat558_Project3_CartronKaranjai"
author: "Matthieu Cartron and Sneha Karanjai"
date: "11/11/2022"
output: html_document
---

# Setup

Note: to hide later if necessary.

## Libraries

```{r lib, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(caret)
```

# Introduction

# Data

```{r readingdata, message=FALSE, warning=FALSE}
unzippedNewDataCSV <- unzip("OnlineNewsPopularity.zip")

newsDataName <- read_csv(unzippedNewDataCSV[1]) # This is the names file
newsData <- read_csv(unzippedNewDataCSV[2])

head(newsData)
```

```{r}
newsData %>% 
  select(starts_with("data_channel_is_"))
```
The 6 groups to analyze are : 

- Lifestyle 
- Entertainment 
- Business
- Social Media 
- Technology 
- World 

```{r subsetdata}
subsettingData <- function(data, area){
  key <- ifelse(tolower(area)=="lifestyle", "lifestyle",
                ifelse(tolower(area)=="entertainment", "entertainment",
                       ifelse(tolower(area)=="business", "bus",
                              ifelse(tolower(area)=="social media", "socmed",
                                     ifelse(tolower(area)=="technology", "tech",
                                            ifelse(tolower(area)=="world", "world", "NA"))))))
  print(key)
  subsetVar <- paste("data_channel_is_", key, sep = "")
  print(as.symbol(subsetVar))
  
  subsetData <- data %>% 
    filter(!!as.symbol(subsetVar)==1)
  
  return(subsetData)
}
```



